import React from 'react'
import { Share2, Download, Mail } from 'lucide-react'
import toast from 'react-hot-toast'

const ShareButton = ({ incident, className = '' }) => {
  const shareIncident = async () => {
    const shareData = {
      title: 'MiraID Incident Report',
      text: `Incident recorded on ${new Date(incident.timestamp).toLocaleString()}\nLocation: ${incident.location}\nType: ${incident.incidentType}`,
      url: window.location.href
    }

    if (navigator.share) {
      try {
        await navigator.share(shareData)
        toast.success('Incident shared successfully!')
      } catch (error) {
        if (error.name !== 'AbortError') {
          fallbackShare(shareData)
        }
      }
    } else {
      fallbackShare(shareData)
    }
  }

  const fallbackShare = (data) => {
    navigator.clipboard.writeText(`${data.title}\n\n${data.text}\n\n${data.url}`)
    toast.success('Incident details copied to clipboard!')
  }

  const downloadSummary = () => {
    const summary = `
MiraID Incident Report
=====================

Date/Time: ${new Date(incident.timestamp).toLocaleString()}
Location: ${incident.location}
Incident Type: ${incident.incidentType}
Summary: ${incident.summary || 'No summary provided'}

Generated by MiraID - Your Instant Know-Your-Rights Guide
    `.trim()

    const blob = new Blob([summary], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `miraid-incident-${incident.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Incident summary downloaded!')
  }

  return (
    <div className={`flex items-center space-x-2 ${className}`}>
      <button
        onClick={shareIncident}
        className="flex items-center space-x-1 px-3 py-2 bg-primary text-white rounded-md hover:bg-blue-700 transition-colors text-sm"
      >
        <Share2 className="h-4 w-4" />
        <span>Share</span>
      </button>
      
      <button
        onClick={downloadSummary}
        className="flex items-center space-x-1 px-3 py-2 bg-accent text-white rounded-md hover:bg-green-600 transition-colors text-sm"
      >
        <Download className="h-4 w-4" />
        <span>Download</span>
      </button>
    </div>
  )
}

export default ShareButton